### ISSUE TITLE
SignOut needs UUID

### ISSUE THREAD

**Issue by jepangLee** [cooktak/luna#6]
각 기기별로 UUID를 각각 생성하고 내부 DB에 담아두는 방식으로 각 기기를 판별하기로 했습니다.
signout할 때 token 테이블에서 해당 기기의 token을 지우기 위해서는

1. Header에 UUID를 같이 보낸다.
2. Token을 만들 때 UUID를 같이 넣어서 Token만 보낸다.

두가지 경우가 있음 어떻게 하는게 좋을까요?

**Comment by park012241** [comment]
2번이 나을 것 같습니다.

**Comment by jepangLee** [comment]
2번으로 할 경우
Token table에서 지울 수 있는 것은 맞지만
해당 기기가 그 토큰의 주인인지를 확인하진 못합니다.

**Comment by park012241** [comment]
> 
> 
> 2번으로 할 경우
> Token table에서 지울 수 있는 것은 맞지만
> 해당 기기가 그 토큰에 맞는 기기인지를 확인하진 못합니다.

확인할 필요가 없다고 생각합니다.
어차피 다른 디바이스의 토큰을 가져올 일이 없으니까요.

**Comment by jepangLee** [comment]
옙

**Comment by park012241** [comment]
아직 코드에 수정사항이 반영되지 않았으므로 Repoen 합니다
